name: Test running tests from the container, no chmod

on:
  workflow_dispatch:

env:
  GHCR_USERNAME: ${{ github.actor }}

jobs:
  test-container-no-chmod:
    name: Test running tests from the container, no chmod
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Clone the Repo
        uses: actions/checkout@v3
      - name: Pull the DevEnv
        run: docker pull "ghcr.io/${GHCR_USERNAME}/kt-devenv:latest"
      - name: Print DevEnv Version
        run: docker run -i "ghcr.io/${GHCR_USERNAME}/kt-devenv:latest" -c v
      - name: Run the Test
        run: |
          ls -lasR example >/dev/null
          tar cf unused_code.tar example
          echo "Hello, World!" > foo.txt
          docker run \
            --mount type=bind,source="$PWD",target=/home/dev/shared \
            -i "ghcr.io/${GHCR_USERNAME}/kt-devenv:latest" \
            -c '(cd /home/dev/shared; ls -las unused_code.tar; ls -las foo.txt; \
                 tar cf foo.txt.tar foo.txt; \
                 echo "CHECKPOINT 1"; \
                 mkdir test; mv foo.txt.tar test; cd test; \
                 echo "CHECKPOINT 2"; \
                 ls -las; tar xf foo.txt.tar; ls -las; cd ..; \
                 echo "CHECKPOINT 3"; \
                 cd /home/dev/shared/example; ls -lasR; \
                 echo -e "=== RUN ===\n"; r; echo -e "=== TEST ===\n"; t)'
                 #            -c '(tar xf shared/code.tar; ls -lasR example; \
                 #                 cd example; echo -e "=== RUN ===\n"; r; echo -e "=== TEST ===\n"; t)'
